#!/usr/bin/env bash

#================================================================
# SCRIPT NAME: 
#   15_prepare_maker_output.sh
#
# DESCRIPTION:
#   This script processes MAKER output files to generate merged GFF3 and FASTA
#   files. The steps involve:
#   1. Merging MAKER GFF3 files with and without sequences.
#   2. Merging FASTA files generated by MAKER into a single output.
#
# USAGE:
#   sbatch 15_prepare_maker_output.sh
#
# DEPENDENCIES:
#   - MAKER: Genome annotation pipeline (specifically gff3_merge and fasta_merge tools).
#   - Correctly configured `assembly_master_datastore_index.log` file generated by MAKER.
#
# INPUT:
#   - MAKER output directory containing the datastore index log file:
#     `$WORKDIR/outputs/14_maker_GENE/assembly.maker.output/assembly_master_datastore_index.log`
#
# OUTPUT:
#   - `assembly.all.maker.gff`: Combined GFF3 file with sequence information.
#   - `assembly.all.maker.noseq.gff`: Combined GFF3 file without sequence information.
#   - `assembly.fasta`: Combined FASTA file of all sequences.
#
# NOTE:
#   - Update `$WORKDIR` and `$COURSEDIR` to match your working environment.
#================================================================

#SBATCH --cpus-per-task=1
#SBATCH --mem=16G
#SBATCH --time=05:00:00
#SBATCH --job-name=maker_output_prep
#SBATCH --mail-user=anna.scarpellinipancrazi@students.unibe.ch
#SBATCH --mail-type=end
#SBATCH --output=/data/users/ascarpellini/assembly_annotation_course/genome_annotation/logs/15_maker_output_prep_output_%j.o
#SBATCH --error=/data/users/ascarpellini/assembly_annotation_course/genome_annotation/logs/15_maker_output_prep_error_%j.e
#SBATCH --partition=pibu_el8

WORKDIR="/data/users/ascarpellini/assembly_annotation_course/genome_annotation"
COURSEDIR="/data/courses/assembly-annotation-course/CDS_annotation"
MAKERBIN="$COURSEDIR/softwares/Maker_v3.01.03/src/bin"
INPUT_FILE="$WORKDIR/outputs/14_maker_GENE/assembly.maker.output/assembly_master_datastore_index.log"
OUTDIR="$WORKDIR/outputs/15_prepared_maker_output"

mkdir -p $OUTDIR
cd $OUTDIR

$MAKERBIN/gff3_merge -s -d $INPUT_FILE > assembly.all.maker.gff
$MAKERBIN/gff3_merge -n -s -d $INPUT_FILE > assembly.all.maker.noseq.gff
$MAKERBIN/fasta_merge -d $INPUT_FILE -o assembly